spring:
  application:
    name: system
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
#    url: jdbc:mysql://localhost:3306/system?characterEncoding=UTF-8&useSSL=false
    url: jdbc:mysql://192.168.99.100:32768/basic_data?characterEncoding=UTF-8&useSSL=false
  redis:
    host: eureka-zuul
#  redis:
#    host: 192.168.99.100
#    port: 32768
#  rabbitmq:
#    host: eureka-zuul
#    username: root
#    password: root
  thymeleaf:
    cache: false
server:
  port: 8801
mybatis:
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com:
      galaxy:
        framework:
          aquarius:
            mapper: debug
eureka:
  client:
    service-url:
      defaultZone: http://eureka-zuul:8101/eureka/